server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
