server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000

services:
  inventory:
    url: http://localhost:8083
  payment:
    url: http://localhost:8085

resilience4j:
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 300ms
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
      payment:
        max-attempts: 3
        wait-duration: 300ms
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
  circuitbreaker:
    instances:
      inventory:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      payment:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,retries
  health:
    circuitbreakers:
      enabled: true
